### ISSUE TITLE
Ca marche pas

### ISSUE THREAD

**Issue by matthias4217** [MasterEwink/law-enforcer#1]
J'arrive pas à lancer le jeu

**Comment by MasterEwink** [comment]
T'as essayé de le recompiler ?

**Comment by matthias4217** [comment]
J'ai fait `make` mais j'ai `make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.`. 🤷

**Comment by MasterEwink** [comment]
Tu peux pull depuis la branch troll, puis réessaie de make.

**Comment by matthias4217** [comment]
Oh c'est bon, merci ! 💚
